"use client";
import { FormEvent, useState } from "react";
import TurnstileWidget from "./TurnstileWidget";

export default function ReaderFeedback({ slug }: { slug: string }) {
  const [open,setOpen]=useState(false); const [helpful,setHelpful]=useState<boolean|undefined>(); const [state,setState]=useState<"idle"|"loading"|"done"|"error">("idle");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("loading");const f=new FormData(event.currentTarget);const payload={articleSlug:slug,helpful,rating:Number(f.get("rating")||0)||undefined,message:String(f.get("message")||""),displayName:String(f.get("displayName")||""),consentPublish:f.get("consentPublish")==="on",turnstileToken:String(f.get("cf-turnstile-response")||"")};try{const r=await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();setState("done");}catch{setState("error");}}
  if(state==="done")return <aside className="readerFeedback success"><small>READER NOTE</small><h3>Thank you — this helps us improve the guide.</h3></aside>;
  return <aside className="readerFeedback"><small>READER NOTE</small><h3>Was this guide useful?</h3><div className="feedbackQuick"><button type="button" onClick={()=>{setHelpful(true);setOpen(true)}} aria-pressed={helpful===true}>Yes, useful</button><button type="button" onClick={()=>{setHelpful(false);setOpen(true)}} aria-pressed={helpful===false}>Not enough yet</button></div>{open&&<form onSubmit={submit}><label>Rating<select name="rating" defaultValue=""><option value="">Optional</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label>What should we know?<textarea name="message" maxLength={1200} rows={4} placeholder="What worked, what was missing, or what you tried…"/></label><label>Display name (optional)<input name="displayName" maxLength={80}/></label><label className="termsCheck"><input type="checkbox" name="consentPublish"/><span>You may publish this note after moderation.</span></label><TurnstileWidget action="reader-feedback"/>{state==="error"&&<small className="formError">That didn&apos;t go through. Please try again.</small>}<button className="secondaryCta" disabled={state==="loading"}>{state==="loading"?"Sending…":"Send feedback"}</button></form>}</aside>;
}
