import Link from "next/link";
import Breadcrumbs from "../components/Breadcrumbs";
import SubFooter from "../components/SubFooter";
import SubHeader from "../components/SubHeader";
import { staticPageMetadata } from "../seo";

export const metadata = staticPageMetadata({ title: 'Field Notes', description: 'How The Curated Pin turns audience signals into focused editorial collections and product ideas.', path: '/case-studies' });

export default function CaseStudiesPage() {
  return <main><SubHeader/><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Field Notes" }]}/><section className="caseHero shell"><small>FIELD NOTES · CASE STUDIES</small><h1>The decisions behind<br/><em>what we publish.</em></h1><p>We document the path from a real audience signal to a focused guide or product concept. If an experiment is still running, we say so. If there is no verified result yet, we do not manufacture one.</p></section><section className="caseStudy shell"><header><span>CASE 01</span><div><small>IN PROGRESS · CELEBRATIONS</small><h2>Why Birthday Parties became the first focused collection</h2><p>A transparent look at how Pinterest demand, Google trend behavior and attainable long-tail competition shaped the launch decision.</p></div></header><div className="caseColumns"><article><b>01 · THE SIGNAL</b><p>Birthday-party searches remained visually strong on Pinterest while age-specific and game-focused queries showed meaningful search demand and manageable competition.</p></article><article><b>02 · THE DECISION</b><p>Build one deep Birthday Parties silo first instead of spreading publishing effort across unrelated categories. Organize it by age, themes, games, food, decorations and practical planning.</p></article><article><b>03 · THE OUTPUT</b><p>A hierarchical taxonomy, an SEO-ready content structure, contextual product opportunities and a publishing system that can later support Crochet and Sewing without rebuilding the site.</p></article><article><b>04 · WHAT COMES NEXT</b><p>Publish the first article cluster, measure Pinterest outbound clicks, Google impressions, email opt-ins and product interactions, then use those signals to choose the next content cluster.</p></article></div><aside><strong>Evidence rule</strong><p>We publish a result only after the underlying analytics can support it. “In progress” is a valid outcome—not a reason to invent a success story.</p></aside></section><section className="caseCta"><div className="shell"><div><small>PLANNING A CELEBRATION?</small><h2>Explore the first focused collection.</h2></div><Link className="primaryCta" href="/category/celebrations/birthday-parties">Visit Birthday Parties</Link></div></section><SubFooter/></main>;
}
