import Breadcrumbs from "../components/Breadcrumbs";
import SubHeader from "../components/SubHeader";
import SubFooter from "../components/SubFooter";
import PrivacyControls from "../components/PrivacyControls";
import { staticPageMetadata } from "../seo";

export const metadata = staticPageMetadata({ title: "Privacy Policy", description: "How The Curated Pin handles accounts, reader feedback, newsletters, analytics, security and privacy choices.", path: "/privacy" });

export default function PrivacyPage() {
  return <main><SubHeader/><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Privacy"}]}/><section className="legalHero shell"><small>PRIVACY POLICY · UPDATED AUGUST 18, 2026</small><h1>Your data should be<br/><em>easy to understand.</em></h1><p>This page explains what the site collects, why it is needed and which choices remain under your control.</p></section><section className="legalBody shell">
    <section><h2>Information you provide</h2><p>We process account details when you register, email addresses when you join the newsletter, password-reset requests, and optional feedback you submit about our guides. Passwords are one-way hashed with a unique salt; we do not store readable passwords.</p></section>
    <section><h2>Accounts, saves and security</h2><p>Signed-in saves are associated with your account. Authentication tokens are stored in secure HTTP-only cookies; a separate anti-CSRF cookie protects authenticated writes. We record limited security events such as failed sign-ins, password changes, role changes and account lockouts to detect abuse. Changing or resetting a password invalidates existing sessions.</p></section>
    <section><h2>Analytics and heatmaps</h2><div><p>We keep privacy-minimized first-party event counts for publication operations, such as article views, content engagement, lead-magnet interactions, saves, affiliate/product clicks and completed newsletter signups. These records do not require an email address for ordinary browsing. If you choose “Accept analytics,” we also create a temporary session identifier in session storage so events within that browser tab can be connected into a funnel, and Google Analytics 4 and Microsoft Clarity are enabled. Clarity may create heatmaps and session-replay data. Advertising storage and personalization remain disabled in our analytics consent configuration. You can decline without losing access to the publication.</p><PrivacyControls/></div></section>
    <section><h2>Bot protection and email delivery</h2><p>Public forms may use Cloudflare Turnstile to distinguish legitimate requests from automated abuse. Password-reset email may be delivered through our transactional email provider. Those processors receive only the information required to provide their service.</p></section>
    <section><h2>Reader feedback and reviews</h2><p>Feedback can include a usefulness vote, optional rating, comment and display name. Feedback is private by default. A comment is eligible for public display only if you explicitly consent and an editor approves it. We may still use private feedback internally to improve an article.</p></section>
    <section><h2>Email subscriptions, lead magnets and segmentation</h2><p>When you request a free resource or join The Sunday Save, we store your email address, optional first name, consent time, signup source, requested lead magnet, relevant topic tags and available UTM campaign values. Topic tags help us send Birthday, Teen Birthday or future craft emails only when they match the interest you requested. Each audience email includes a preferences/unsubscribe route. Unsubscribing cancels active nurture sequences for that address.</p></section><section><h2>Affiliate, product and campaign measurement</h2><p>We distinguish ordinary outbound links, affiliate clicks, owned-product clicks, checkout intent and semantic internal-link clicks so editorial decisions are not based on a single generic click count. UTM source, medium, campaign, content and term values may be stored when present. If our checkout provider later confirms a purchase through a protected server-to-server webhook, we may store the product, amount, currency and non-sensitive attribution fields needed to measure the sale. Affiliate and checkout destinations apply their own privacy practices after you leave this site.</p></section>
    <section><h2>Retention and safeguards</h2><p>Access is role-controlled, writes are validated server-side, request bodies are capped, database queries are parameterized, and sensitive configuration is kept in server-side environment variables. We retain information only as long as needed for the stated purpose, security, operations and legal obligations.</p></section>
    <section><h2>Your choices</h2><p>You may decline analytics, unsubscribe from newsletter emails, clear device-local preferences, or request account/subscription assistance at the-curated-pin@gmail.com. If you previously accepted analytics, use the privacy controls above to change your preference.</p></section>
  </section><SubFooter/></main>;
}
