CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(80) NOT NULL,
  path VARCHAR(260) NOT NULL UNIQUE,
  intro VARCHAR(700) NOT NULL DEFAULT '',
  color CHAR(7) NOT NULL DEFAULT '#e8e4db' CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
  mark VARCHAR(16) NOT NULL DEFAULT '•',
  status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  show_in_nav BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS categories_parent_sort_idx ON categories(parent_id, sort_order, name);
CREATE INDEX IF NOT EXISTS categories_status_nav_idx ON categories(status, show_in_nav, sort_order);

-- First live vertical: Celebrations -> Birthday Parties.
INSERT INTO categories (name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
VALUES ('Celebrations', 'celebrations', 'celebrations', 'Useful planning ideas for birthdays, parties and milestones worth celebrating.', '#eadfd2', '✦', 'active', TRUE, 10)
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, 'Birthday Parties', 'birthday-parties', 'celebrations/birthday-parties', 'Birthday ideas organized by age, theme, games, food and practical planning.', '#efd9cf', '🎉', 'active', TRUE, 11
FROM categories WHERE path = 'celebrations'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, seed.name, seed.slug, 'celebrations/birthday-parties/' || seed.slug, seed.intro, seed.color, seed.mark, 'active', FALSE, seed.sort_order
FROM categories parent
CROSS JOIN (VALUES
  ('Birthday Ideas by Age', 'by-age', 'Age-specific birthday ideas, from first birthdays through milestone celebrations.', '#f0dfd2', '01', 10),
  ('Teen Birthdays', 'teen-birthdays', 'Party ideas, themes, games and practical plans for teenagers.', '#e8d9df', '13+', 20),
  ('First Birthdays', 'first-birthdays', 'Thoughtful first-birthday themes, planning ideas and celebration details.', '#eee2c7', '1', 30),
  ('Party Themes', 'party-themes', 'Birthday themes with decoration, activity and food ideas that work together.', '#dfe7d7', '✦', 40),
  ('Party Games', 'party-games', 'Group games and birthday activities organized by age, setting and energy level.', '#dce8e2', '↗', 50),
  ('Party Food', 'party-food', 'Practical party food, snack and serving ideas for different kinds of celebrations.', '#efe1c9', '◇', 60),
  ('Decorations', 'decorations', 'Decoration ideas, setup guides and shopping inspiration for birthday parties.', '#ead7d2', '✹', 70),
  ('Printables & Planners', 'printables-planners', 'Planning sheets, checklists, games and printable resources for easier party prep.', '#dddbea', '▤', 80)
) AS seed(name, slug, intro, color, mark, sort_order)
WHERE parent.path = 'celebrations/birthday-parties'
ON CONFLICT(path) DO NOTHING;

-- Future verticals are seeded but intentionally inactive until their content libraries are ready.
INSERT INTO categories (name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
VALUES
  ('Crafts', 'crafts', 'crafts', 'Patterns, projects and practical guides for making things by hand.', '#dce5dc', '✂', 'inactive', FALSE, 20),
  ('Style', 'style', 'style', 'Focused personal-style edits, useful guides and wearable inspiration.', '#e6dce1', '◇', 'inactive', FALSE, 30)
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, 'Crochet', 'crochet', 'crafts/crochet', 'Crochet patterns, project ideas, beginner help and tool recommendations.', '#dfe6d6', '🧶', 'inactive', FALSE, 10
FROM categories WHERE path = 'crafts'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, seed.name, seed.slug, 'crafts/crochet/' || seed.slug, seed.intro, seed.color, seed.mark, 'inactive', FALSE, seed.sort_order
FROM categories parent
CROSS JOIN (VALUES
  ('Crochet Flowers', 'flowers', 'Flower and bouquet crochet projects with strong visual and seasonal appeal.', '#eadeda', '🌸', 10),
  ('Crochet Blankets', 'blankets', 'Evergreen crochet blanket projects, sizing help and yarn guidance.', '#e7dfcf', '▦', 20),
  ('Crochet Bags', 'bags', 'Crochet bag projects, patterns, construction ideas and finishing details.', '#ddd9ce', '◫', 30),
  ('Beginner Crochet', 'beginner', 'Beginner-friendly crochet techniques, stitches, projects and learning guides.', '#dfe7dc', '01', 40),
  ('Tools & Yarn', 'tools-yarn', 'Crochet hooks, yarn, kits and practical buying guides.', '#d9e1df', '↗', 50)
) AS seed(name, slug, intro, color, mark, sort_order)
WHERE parent.path = 'crafts/crochet'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, 'Sewing', 'sewing', 'crafts/sewing', 'Easy sewing projects, patterns, beginner guidance and quilting ideas.', '#e4dfd3', '🧵', 'inactive', FALSE, 20
FROM categories WHERE path = 'crafts'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, seed.name, seed.slug, 'crafts/sewing/' || seed.slug, seed.intro, seed.color, seed.mark, 'inactive', FALSE, seed.sort_order
FROM categories parent
CROSS JOIN (VALUES
  ('Beginner Projects', 'beginner-projects', 'Easy sewing projects designed for beginners and quick wins.', '#e4dfd3', '01', 10),
  ('Sewing Patterns', 'patterns', 'Useful sewing-pattern collections and project-specific pattern guides.', '#ddd9d2', '▤', 20),
  ('Quilting', 'quilting', 'Quilting projects, beginner blocks, patterns and technique guides.', '#dce3dc', '▦', 30)
) AS seed(name, slug, intro, color, mark, sort_order)
WHERE parent.path = 'crafts/sewing'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, seed.name, seed.slug, 'style/' || seed.slug, seed.intro, seed.color, seed.mark, 'inactive', FALSE, seed.sort_order
FROM categories parent
CROSS JOIN (VALUES
  ('Nails', 'nails', 'Wearable nail ideas, seasonal edits and practical design guides.', '#ead4da', '✦', 10),
  ('Capsule Wardrobe', 'capsule-wardrobe', 'Capsule wardrobe planning, seasonal edits and practical outfit systems.', '#e6ddd5', '◇', 20)
) AS seed(name, slug, intro, color, mark, sort_order)
WHERE parent.path = 'style'
ON CONFLICT(path) DO NOTHING;

INSERT INTO categories (parent_id, name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
SELECT id, 'Weddings', 'weddings', 'celebrations/weddings', 'Wedding planning ideas, templates, stationery and useful celebration guides.', '#eee1dc', '♡', 'inactive', FALSE, 90
FROM categories WHERE path = 'celebrations'
ON CONFLICT(path) DO NOTHING;

-- Preserve legacy/demo articles without keeping their old taxonomy public.
INSERT INTO categories (name, slug, path, intro, color, mark, status, show_in_nav, sort_order)
VALUES ('Archive', 'archive', 'archive', 'Legacy content retained during the editorial pivot.', '#e2e2de', '·', 'inactive', FALSE, 999)
ON CONFLICT(path) DO NOTHING;

ALTER TABLE articles ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT;
UPDATE articles
SET category_id = (SELECT id FROM categories WHERE path = 'archive' LIMIT 1)
WHERE category_id IS NULL;
ALTER TABLE articles ALTER COLUMN category_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS articles_category_idx ON articles(category_id, status, published_at DESC);
