CREATE TABLE IF NOT EXISTS seo_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR(180) NOT NULL UNIQUE,
  entity_type VARCHAR(20) NOT NULL CHECK (entity_type IN ('category', 'article')),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  article_id BIGINT REFERENCES articles(id) ON DELETE SET NULL,
  planned_slug VARCHAR(120),
  title VARCHAR(200) NOT NULL,
  page_role VARCHAR(20) NOT NULL CHECK (page_role IN ('hub', 'pillar', 'thematic', 'supporting', 'money', 'utility')),
  cluster_key VARCHAR(80) NOT NULL,
  primary_keyword VARCHAR(180) NOT NULL,
  search_intent VARCHAR(24) NOT NULL DEFAULT 'informational' CHECK (search_intent IN ('informational', 'commercial', 'transactional', 'mixed', 'navigational')),
  semantic_scope TEXT NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'research' CHECK (status IN ('research', 'planned', 'briefed', 'published', 'hold')),
  priority INTEGER NOT NULL DEFAULT 100 CHECK (priority BETWEEN 1 AND 999),
  target_volume INTEGER CHECK (target_volume IS NULL OR target_volume >= 0),
  target_kd INTEGER CHECK (target_kd IS NULL OR target_kd BETWEEN 0 AND 100),
  target_cpc NUMERIC(10,2) CHECK (target_cpc IS NULL OR target_cpc >= 0),
  backlink_priority INTEGER NOT NULL DEFAULT 1 CHECK (backlink_priority BETWEEN 0 AND 5),
  page_rank_score NUMERIC(14,10) NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (entity_type = 'category' AND category_id IS NOT NULL AND planned_slug IS NULL)
    OR
    (entity_type = 'article' AND planned_slug IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS seo_pages_cluster_priority_idx ON seo_pages(cluster_key, priority, page_role);
CREATE INDEX IF NOT EXISTS seo_pages_article_idx ON seo_pages(article_id);
CREATE INDEX IF NOT EXISTS seo_pages_category_idx ON seo_pages(category_id);

CREATE TABLE IF NOT EXISTS seo_keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seo_page_id BIGINT NOT NULL REFERENCES seo_pages(id) ON DELETE CASCADE,
  keyword VARCHAR(220) NOT NULL,
  keyword_role VARCHAR(20) NOT NULL DEFAULT 'secondary' CHECK (keyword_role IN ('primary', 'secondary', 'supporting', 'excluded')),
  volume INTEGER CHECK (volume IS NULL OR volume >= 0),
  kd INTEGER CHECK (kd IS NULL OR kd BETWEEN 0 AND 100),
  cpc NUMERIC(10,2) CHECK (cpc IS NULL OR cpc >= 0),
  intent VARCHAR(24) NOT NULL DEFAULT 'informational' CHECK (intent IN ('informational', 'commercial', 'transactional', 'mixed', 'navigational')),
  source VARCHAR(80) NOT NULL DEFAULT 'manual',
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(seo_page_id, keyword)
);
CREATE INDEX IF NOT EXISTS seo_keywords_keyword_idx ON seo_keywords(LOWER(keyword));
CREATE INDEX IF NOT EXISTS seo_keywords_page_role_idx ON seo_keywords(seo_page_id, keyword_role);

CREATE TABLE IF NOT EXISTS seo_internal_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_page_id BIGINT NOT NULL REFERENCES seo_pages(id) ON DELETE CASCADE,
  target_page_id BIGINT NOT NULL REFERENCES seo_pages(id) ON DELETE CASCADE,
  anchor_text VARCHAR(180) NOT NULL,
  link_type VARCHAR(20) NOT NULL CHECK (link_type IN ('parent', 'child', 'sibling', 'contextual', 'commercial', 'conversion')),
  placement VARCHAR(20) NOT NULL DEFAULT 'body' CHECK (placement IN ('body', 'hub', 'related', 'cta')),
  semantic_score INTEGER NOT NULL CHECK (semantic_score BETWEEN 0 AND 100),
  weight NUMERIC(8,3) NOT NULL DEFAULT 1.000 CHECK (weight > 0),
  required BOOLEAN NOT NULL DEFAULT TRUE,
  rationale TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (source_page_id <> target_page_id),
  UNIQUE(source_page_id, target_page_id, anchor_text)
);
CREATE INDEX IF NOT EXISTS seo_internal_links_source_idx ON seo_internal_links(source_page_id, required, weight DESC);
CREATE INDEX IF NOT EXISTS seo_internal_links_target_idx ON seo_internal_links(target_page_id, weight DESC);
CREATE INDEX IF NOT EXISTS seo_internal_links_semantic_idx ON seo_internal_links(semantic_score);

CREATE TABLE IF NOT EXISTS seo_backlink_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seo_page_id BIGINT NOT NULL REFERENCES seo_pages(id) ON DELETE CASCADE,
  asset_name VARCHAR(200) NOT NULL,
  asset_type VARCHAR(40) NOT NULL,
  outreach_angle TEXT NOT NULL DEFAULT '',
  target_audience TEXT NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'building', 'live', 'outreach', 'earned', 'retired')),
  priority INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(seo_page_id, asset_name)
);

-- Link an SEO article plan automatically when the matching article already exists.
UPDATE seo_pages p
SET article_id = a.id, updated_at = CURRENT_TIMESTAMP
FROM articles a
WHERE p.entity_type = 'article' AND p.planned_slug = a.slug AND p.article_id IS DISTINCT FROM a.id;
