ALTER TABLE newsletter_subscribers ALTER COLUMN source TYPE VARCHAR(80);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS last_source VARCHAR(80) NOT NULL DEFAULT 'website';
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS primary_interest VARCHAR(80);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS lead_magnet_slug VARCHAR(120);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS last_article_slug VARCHAR(120);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS last_category_path VARCHAR(240);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS utm_source VARCHAR(120);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(120);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS utm_campaign VARCHAR(160);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS utm_content VARCHAR(160);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS utm_term VARCHAR(160);
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS consent_at TIMESTAMPTZ;
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS consent_version VARCHAR(40) NOT NULL DEFAULT 'email-v1';
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE newsletter_subscribers ADD COLUMN IF NOT EXISTS unsubscribed_at TIMESTAMPTZ;

UPDATE newsletter_subscribers
SET last_source = COALESCE(NULLIF(source, ''), 'website'),
    consent_at = COALESCE(consent_at, created_at),
    updated_at = COALESCE(updated_at, created_at)
WHERE consent_at IS NULL OR last_source = '';

CREATE TABLE IF NOT EXISTS audience_interests (
  interest_key VARCHAR(80) PRIMARY KEY,
  parent_key VARCHAR(80) REFERENCES audience_interests(interest_key) ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS newsletter_subscriber_interests (
  subscriber_id BIGINT NOT NULL REFERENCES newsletter_subscribers(id) ON DELETE CASCADE,
  interest_key VARCHAR(80) NOT NULL REFERENCES audience_interests(interest_key) ON DELETE CASCADE,
  source VARCHAR(80) NOT NULL DEFAULT 'signup',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(subscriber_id, interest_key)
);
CREATE INDEX IF NOT EXISTS subscriber_interests_interest_idx ON newsletter_subscriber_interests(interest_key, created_at DESC);

CREATE TABLE IF NOT EXISTS lead_magnets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  eyebrow VARCHAR(80) NOT NULL DEFAULT 'FREE DOWNLOAD',
  description VARCHAR(800) NOT NULL,
  cta_label VARCHAR(100) NOT NULL DEFAULT 'Get the free guide',
  interest_key VARCHAR(80) REFERENCES audience_interests(interest_key) ON DELETE SET NULL,
  asset_url TEXT NOT NULL DEFAULT '',
  resource_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  email_subject VARCHAR(180) NOT NULL DEFAULT '',
  email_intro VARCHAR(1000) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','retired')),
  seo_index BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS lead_magnets_status_idx ON lead_magnets(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS lead_magnet_targets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_magnet_id BIGINT NOT NULL REFERENCES lead_magnets(id) ON DELETE CASCADE,
  target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('global','category','article')),
  target_key VARCHAR(240) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 50,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(lead_magnet_id, target_type, target_key)
);
CREATE INDEX IF NOT EXISTS lead_magnet_targets_lookup_idx ON lead_magnet_targets(target_type, target_key, priority DESC);

CREATE TABLE IF NOT EXISTS email_sequences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  interest_key VARCHAR(80) REFERENCES audience_interests(interest_key) ON DELETE SET NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','retired')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_sequence_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id BIGINT NOT NULL REFERENCES email_sequences(id) ON DELETE CASCADE,
  step_number INTEGER NOT NULL CHECK (step_number > 0),
  delay_hours INTEGER NOT NULL DEFAULT 24 CHECK (delay_hours >= 0),
  subject VARCHAR(180) NOT NULL,
  preheader VARCHAR(240) NOT NULL DEFAULT '',
  body_text VARCHAR(5000) NOT NULL,
  cta_label VARCHAR(120) NOT NULL DEFAULT '',
  cta_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(sequence_id, step_number)
);

CREATE TABLE IF NOT EXISTS subscriber_sequence_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT NOT NULL REFERENCES newsletter_subscribers(id) ON DELETE CASCADE,
  sequence_id BIGINT NOT NULL REFERENCES email_sequences(id) ON DELETE CASCADE,
  current_step INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0,
  next_send_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','completed','cancelled')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(subscriber_id, sequence_id)
);
CREATE INDEX IF NOT EXISTS sequence_enrollments_due_idx ON subscriber_sequence_enrollments(status, next_send_at);

CREATE TABLE IF NOT EXISTS email_delivery_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT REFERENCES newsletter_subscribers(id) ON DELETE SET NULL,
  sequence_id BIGINT REFERENCES email_sequences(id) ON DELETE SET NULL,
  step_id BIGINT REFERENCES email_sequence_steps(id) ON DELETE SET NULL,
  message_type VARCHAR(40) NOT NULL,
  provider_message_id VARCHAR(200),
  status VARCHAR(20) NOT NULL CHECK (status IN ('sent','skipped','failed')),
  error_message VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS email_delivery_logs_subscriber_idx ON email_delivery_logs(subscriber_id, created_at DESC);
CREATE INDEX IF NOT EXISTS email_delivery_logs_status_idx ON email_delivery_logs(status, created_at DESC);
