export type ShopProduct = {
  slug: string;
  name: string;
  shortName: string;
  price: string;
  priceValue: number;
  currency: "USD";
  eyebrow: string;
  description: string;
  longDescription: string;
  pages: number;
  coverImage: string;
  checkoutEnv: string;
  checkoutUrl?: string;
  leadMagnet?: string;
  category?: "parties" | "crochet";
  ctaLabel?: string;
  isFree?: boolean;
  freeDownloadUrl?: string;
  includes: string[];
  bestFor: string[];
  faqs: Array<{ question: string; answer: string }>;
};

export const shopProducts: ShopProduct[] = [
  {
    slug: "ultimate-birthday-party-planner",
    name: "Ultimate Birthday Party Planner",
    shortName: "The Birthday Party Planner",
    price: "$12",
    priceValue: 12,
    currency: "USD",
    eyebrow: "THE CURATED PIN SHOP",
    description: "A beautifully designed 29-page printable birthday-party planning system with budget worksheets, guest tracking, menus, activities, timelines and calm day-of checklists.",
    longDescription: "From the first saved idea to the final thank-you note, this thoughtfully designed 29-page workbook turns a hundred scattered decisions into one clear, confidence-building plan. Built for real budgets, real homes and celebrations that feel every bit as good as they look.",
    pages: 29,
    coverImage: "/shop/ultimate-birthday-party-planner-cover.png",
    checkoutEnv: "CHECKOUT_URL_ULTIMATE_BIRTHDAY_PARTY_PLANNER",
    checkoutUrl: "https://isafouat.gumroad.com/l/ultimate-birthday-party-planner",
    leadMagnet: "/free/birthday-party-quick-start-kit",
    category: "parties",
    ctaLabel: "Get the planner ($12) →",
    includes: [
      "The signature one-page party brief and celebration priorities",
      "A clear category-by-category budget and reusable expense tracker",
      "Guest, RSVP, allergy and dietary-preference planning",
      "Venue comparisons, layout notes and practical logistics",
      "A considered visual-direction and decoration worksheet",
      "Guest-count-led menu, cake and serving plans",
      "An anchor activity, backup ideas and original games bank",
      "Shopping, orders, deliveries and favor checklists",
      "Four-week, seven-day and party-day timelines",
      "Weather, accessibility, thank-you and reflection pages",
    ],
    bestFor: ["Parents planning kids or teen birthdays", "Adults planning milestone birthdays", "At-home or venue-based parties", "Anyone who wants one source of truth instead of scattered notes"],
    faqs: [
      { question: "Is this an editable Canva template?", answer: "No. The launch version is a clean printable PDF workbook designed for handwriting, tablet annotation or digital PDF markup." },
      { question: "Can I reuse it?", answer: "Yes, for your own personal birthday planning. Print or duplicate the file for future birthdays in your household. Resale or redistribution is not included." },
      { question: "Do I need every page?", answer: "No. The planner is modular. Use the pages that match the party you are actually planning." },
      { question: "Is this the same as the free Quick-Start Kit?", answer: "No. The free kit covers the essential planning decisions. This paid workbook adds detailed budget, venue, quantity, setup, countdown and follow-up pages." },
    ],
  },
  {
    slug: "teen-birthday-party-planner",
    name: "The Teen Party Playbook + Games Pack",
    shortName: "The Teen Party Playbook",
    price: "$14",
    priceValue: 14,
    currency: "USD",
    eyebrow: "TEEN PARTY TOOLKIT",
    description: "A stylish 27-page Teen Birthday Planner + Games Pack with vibe boards, party blueprints, original printable photo prompts and genuinely low-pressure activities.",
    longDescription: "A better teen party starts with the right vibe, not a forced itinerary. This beautifully designed 27-page playbook brings together flexible planning pages, movie-night and sleepover blueprints, original printable games and photo challenges that guests can actually choose to enjoy.",
    pages: 27,
    coverImage: "/shop/teen-birthday-party-planner-cover.png",
    checkoutEnv: "CHECKOUT_URL_TEEN_BIRTHDAY_PARTY_PLANNER",
    checkoutUrl: "https://isafouat.gumroad.com/l/teen-birthday-party-planner",
    leadMagnet: "/free/teen-birthday-party-planning-kit",
    category: "parties",
    ctaLabel: "Get the playbook ($14) →",
    includes: [
      "A teen-approved vibe selector and one-page party brief",
      "Guest-list, budget, boundaries and accessibility planning",
      "Movie-night, sleepover, spa and backyard party blueprints",
      "A creative-studio and karaoke-night planning page",
      "Snack-bar, playlist, lighting and flexible timeline planners",
      "A consent-first photo moment and scavenger hunt",
      "Original This-or-That and Would-You-Rather printable cards",
      "A friendly emoji challenge and conversation-starter deck",
      "An eight-player mini-tournament and challenge scoreboard",
      "Low-pressure one-minute games, setup notes and thank-yous",
    ],
    bestFor: ["Ages roughly 13-18", "Sleepovers and movie nights", "Small or medium friend groups", "Parents and teens planning together"],
    faqs: [
      { question: "Are the games mandatory or highly structured?", answer: "No. They are optional tools for arrivals, downtime and groups that want an activity. The pack deliberately leaves room for unstructured hangout time." },
      { question: "Does it use copyrighted characters or branded themes?", answer: "No. The pack is original and brand-neutral, so it can work with many party styles." },
      { question: "Can the teen fill it out too?", answer: "Yes. The vibe, activity and playlist pages are especially useful to complete together." },
      { question: "What is different from the free Teen Planning Kit?", answer: "The paid pack adds detailed planning sheets plus original printable games, photo prompts, scoreboards and challenge pages." },
    ],
  },
  {
    slug: "pips-the-pumpkin",
    name: "Pips the Pumpkin Crochet Pattern",
    shortName: "Pips the Pumpkin",
    price: "$5.99",
    priceValue: 5.99,
    currency: "USD",
    eyebrow: "CROCHET AMIGURUMI PATTERN",
    description: "Create Pips the Pumpkin — an adorable amigurumi plush with sweet smiling face, rosy cheeks, little arms and feet, and detailed pumpkin stalk.",
    longDescription: "Create your own adorable autumn friend with the Pips the Pumpkin Amigurumi Crochet Pattern! This charming digital PDF tutorial guides you step-by-step through making a cute pumpkin plush with a sweet smiling face, rosy cheeks, little arms and feet, and a detailed pumpkin stalk. Perfect for Halloween decorations, fall home decor, and handmade gifts.",
    pages: 4,
    coverImage: "/article-media/crochet/pumpkin_kitchen.png",
    checkoutEnv: "CHECKOUT_URL_PIPS_THE_PUMPKIN",
    checkoutUrl: "https://isafouat.gumroad.com/l/PipsthePumpkin",
    leadMagnet: "/category/crafts/crochet",
    category: "crochet",
    ctaLabel: "Get the pattern ($5.99) →",
    includes: [
      "Digital PDF crochet pattern with step-by-step instructions",
      "Written using US crochet terminology with UK terms included",
      "Detailed stalk, rosy cheeks, arms, and feet shaping guidance",
      "Yarn requirements (Cotton Aran in orange, green, and pink)",
      "Safety eyes, stuffing, and assembly finishing tips",
    ],
    bestFor: ["Halloween crochet projects", "Fall and Thanksgiving home decor", "Amigurumi lovers & collectors", "Handmade seasonal gifts"],
    faqs: [
      { question: "What skill level is required?", answer: "This is an intermediate/confident-beginner amigurumi pattern. You should know magic ring, single crochet, increases, decreases, and basic assembly." },
      { question: "What materials do I need?", answer: "Cotton Aran yarn (orange, green, pink), a 4mm (US G/6) crochet hook, 10mm safety eyes, toy stuffing, and a yarn needle." },
      { question: "Is this a physical item?", answer: "No, this listing is for an instant digital PDF pattern download." },
    ],
  },
  {
    slug: "oscar-the-little-bat",
    name: "Oscar the Little Bat Crochet Pattern",
    shortName: "Oscar the Little Bat",
    price: "$5.99",
    priceValue: 5.99,
    currency: "USD",
    eyebrow: "CROCHET AMIGURUMI PATTERN",
    description: "Create Oscar the Little Bat — a charming amigurumi bat plush with little ears, wings, tummy, tiny feet, embroidered nose, and sweet little teeth.",
    longDescription: "Create your own adorable handmade bat plush with the Oscar the Little Bat Amigurumi Crochet Pattern! This detailed PDF pattern guides you through making a cute crochet bat with charming details including his little ears, wings, tummy, tiny feet, embroidered nose, and sweet little teeth. Perfect for Halloween decorations, gifts, or cute animal amigurumi collections.",
    pages: 4,
    coverImage: "/article-media/crochet/ghost_bat_halloween.png",
    checkoutEnv: "CHECKOUT_URL_OSCAR_THE_LITTLE_BAT",
    checkoutUrl: "https://isafouat.gumroad.com/l/OscartheLittleBat",
    leadMagnet: "/category/crafts/crochet",
    category: "crochet",
    ctaLabel: "Get the pattern ($5.99) →",
    includes: [
      "Digital PDF crochet pattern with comprehensive instructions",
      "Written in US terminology with UK terms included",
      "Step-by-step guidance for wings, body, ears, and facial details",
      "Assembly instructions and finishing tips for tabletop stability",
    ],
    bestFor: ["Halloween crochet projects", "Cute animal amigurumi collections", "Handmade spooky-season gifts", "Nursery and shelf decor"],
    faqs: [
      { question: "What is the finished size?", answer: "Approximately 6 inches / 15 cm tall depending on your yarn tension and hook size." },
      { question: "What materials are needed?", answer: "Cotton Aran yarn, a 4mm (US G/6) crochet hook, 10mm safety eyes, toy stuffing, and an embroidery yarn needle." },
      { question: "Is it beginner-friendly?", answer: "It is suitable for adventurous beginners and intermediate crocheters familiar with spiral rounds and piece assembly." },
    ],
  },
  {
    slug: "amigurumi-ghost-crochet",
    name: "Amigurumi Ghost Crochet Pattern",
    shortName: "Amigurumi Ghost",
    price: "$5.99",
    priceValue: 5.99,
    currency: "USD",
    eyebrow: "CROCHET AMIGURUMI PATTERN",
    description: "Create an adorable friendly ghost with a pointed witch hat — perfect for Halloween decorations, cozy plushies, and autumn crafting.",
    longDescription: "Create your own adorable crochet ghost with this digital amigurumi crochet pattern! Perfect for crochet lovers who enjoy handmade plushies, Halloween decorations, and cozy DIY projects. Features a friendly rounded ghost body, pointed witch hat, and clear step-by-step guidance.",
    pages: 4,
    coverImage: "/article-media/crochet/halloween_ghost_pumpkin_bat.png",
    checkoutEnv: "CHECKOUT_URL_AMIGURUMI_GHOST_CROCHET",
    checkoutUrl: "https://isafouat.gumroad.com/l/AmigurumiGhostCrochet",
    leadMagnet: "/category/crafts/crochet",
    category: "crochet",
    ctaLabel: "Get the pattern ($5.99) →",
    includes: [
      "Digital PDF pattern with clear step-by-step instructions",
      "Rounded ghost body and pointed witch hat construction",
      "Materials list, abbreviations, and assembly tips",
      "Facial embroidery and safety eye placement guide",
    ],
    bestFor: ["Halloween home decor", "Cute amigurumi plushie lovers", "Handmade autumn gifts", "Weekend crochet projects"],
    faqs: [
      { question: "Is this a digital download?", answer: "Yes, you will receive immediate access to download the PDF pattern upon purchase." },
      { question: "Can I sell items made from this pattern?", answer: "Review the personal use licensing terms included in the pattern before selling finished handmade items." },
    ],
  },
  {
    slug: "bernard-amigurumi-dino",
    name: "Bernard The Dinosaur Crochet Pattern",
    shortName: "Bernard the Dinosaur",
    price: "$5.99",
    priceValue: 5.99,
    currency: "USD",
    eyebrow: "CROCHET AMIGURUMI PATTERN",
    description: "Meet Bernard the Dinosaur — a sweet, cuddly amigurumi dinosaur featuring a rounded body, cute cheeks, tiny arms, textured back spikes, and freestanding legs.",
    longDescription: "Bring this adorable little dinosaur to life with your crochet hook! Bernard is a sweet, cuddly dinosaur amigurumi design featuring a rounded body, cute cheeks, tiny arms, textured spikes, and a playful smile. This digital pattern guides you through creating your own handmade dinosaur plush with sturdy freestanding balance.",
    pages: 6,
    coverImage: "/article-media/crochet/dino-1.png",
    checkoutEnv: "CHECKOUT_URL_BERNARD_AMIGURUMI_DINO",
    checkoutUrl: "https://isafouat.gumroad.com/l/BernardAmigurumiDino",
    leadMagnet: "/category/crafts/crochet",
    category: "crochet",
    ctaLabel: "Get the pattern ($5.99) →",
    includes: [
      "Digital PDF pattern with step-by-step written instructions",
      "Balanced 4-leg standing assembly and counterbalance tail guide",
      "Dorsal spine spikes placement and contrast color tips",
      "Color inspiration guide and finished size measurements (~7 in / 18 cm tall)",
    ],
    bestFor: ["Dinosaur lovers & nursery decor", "Handmade baby and birthday gifts", "Amigurumi collectors", "Intermediate crocheters"],
    faqs: [
      { question: "How tall is the finished dinosaur?", answer: "Approximately 7 inches / 18 cm tall with DK/worsted yarn and standard hook." },
      { question: "Does it stand on its own?", answer: "Yes! The pattern includes flat-pad legs and a curved tail engineered as a functional tripod for stable tabletop standing." },
    ],
  },
  {
    slug: "halloween-crochet-bundle",
    name: "Halloween Crochet Pattern Bundle",
    shortName: "Halloween Pattern Bundle",
    price: "$19",
    priceValue: 19,
    currency: "USD",
    eyebrow: "4-IN-1 PATTERN BUNDLE",
    description: "The complete Halloween crew in one digital ebook: Bernard the Dinosaur, Boo the Friendly Ghost, Oscar the Bat, and Pips the Pumpkin.",
    longDescription: "Create your own adorable spooky crochet collection with this Halloween Amigurumi Crochet Pattern Bundle! This digital crochet ebook includes 4 cute Halloween-themed toy patterns: Bernard the Dinosaur, Boo the Friendly Ghost, Oscar the Bat, and Pips the Pumpkin. Perfect for fall crafting, handmade gifts, seasonal decor, and amigurumi lovers.",
    pages: 18,
    coverImage: "/article-media/crochet/halloween_ghost_pumpkin_bat.png",
    checkoutEnv: "CHECKOUT_URL_HALLOWEEN_CROCHET_BUNDLE",
    checkoutUrl: "https://isafouat.gumroad.com/l/HalloweenCrochetBundle",
    leadMagnet: "/category/crafts/crochet",
    category: "crochet",
    ctaLabel: "Get the 4-pattern bundle ($19) →",
    includes: [
      "All 4 complete amigurumi patterns in one comprehensive bundle",
      "Bernard the Dinosaur, Boo the Friendly Ghost, Oscar the Bat & Pips the Pumpkin",
      "Detailed stitch guides, assembly photos, and finishing techniques",
      "Finished sizes approximately 6–8 inches / 15–20 cm tall",
    ],
    bestFor: ["Making a coordinated seasonal plushie display", "Fall craft fairs and holiday gifting", "Crochet toy enthusiasts wanting the complete set", "Best value saving compared to individual patterns"],
    faqs: [
      { question: "Are all 4 patterns included in one download?", answer: "Yes! You receive all 4 complete, printable PDF patterns together in this bundle." },
      { question: "What terminology is used?", answer: "All patterns are written in standard US crochet terminology with UK equivalents noted." },
    ],
  },
  {
    slug: "balcony-bralette",
    name: "The Balcony Bralette Crochet Pattern",
    shortName: "The Balcony Bralette",
    price: "FREE",
    priceValue: 0,
    currency: "USD",
    eyebrow: "FREE CROCHET PATTERN",
    description: "A stylish, wearable handmade crochet bralette with step-by-step cup shaping, adjustable sizing (81–147 cm), and versatile summer styling.",
    longDescription: "Create a beautiful handmade crochet bralette with this easy wearable pattern. Perfect for summer outfits, layering, festivals, and makers who want stylish DIY clothing. Enter your email to receive the complete printable PDF pattern tutorial immediately.",
    pages: 14,
    coverImage: "/article-media/crochet/bralette-1.png",
    checkoutEnv: "",
    checkoutUrl: "/free/crochet-bralette-pattern",
    leadMagnet: "/free/crochet-bralette-pattern",
    category: "crochet",
    isFree: true,
    freeDownloadUrl: "/free/crochet-bralette-pattern",
    ctaLabel: "Download free pattern PDF →",
    includes: [
      "Complete 14-page printable PDF garment tutorial",
      "Multiple size grades covering 81 cm to 147 cm chest measurements",
      "Foundation row, shaping, and symmetry guidelines",
      "Underbust band and adjustable strap construction",
      "Yarn recommendations and styling inspiration",
    ],
    bestFor: ["Summer outfits and festival fashion", "First-time crochet garment makers", "Custom size-inclusive fit", "Handmade wardrobe building"],
    faqs: [
      { question: "Is this pattern completely free?", answer: "Yes! Enter your email to receive immediate access to the full Balcony Bralette PDF pattern." },
      { question: "Is this suitable for beginners?", answer: "Yes. It is classified as an easy wearable project with straightforward stitch repeats and step-by-step photos." },
      { question: "What sizes are covered?", answer: "Multiple size variations are provided covering chest measurements from 81 cm up to 147 cm." },
    ],
  },
  {
    slug: "rainbow-ripple-baby-blanket",
    name: "Rainbow Ripple Baby Blanket Crochet Pattern",
    shortName: "Rainbow Ripple Blanket",
    price: "$5.99",
    priceValue: 5.99,
    currency: "USD",
    eyebrow: "CROCHET BLANKET PATTERN",
    description: "Create a timeless heirloom chevron ripple baby blanket with clear color sequences, exact stitch counts, gentle wave shaping, and safe border finishing.",
    longDescription: "Bring gentle waves of color into your nursery with the Rainbow Ripple Baby Blanket Crochet Pattern! This detailed digital PDF tutorial guides you step-by-step through creating a timeless chevron ripple blanket with clean peak-and-valley stitch counts, seamless color changes, and a neat border that lays flat. Perfect for baby showers, handmade gifts, and relaxing sofa crochet.",
    pages: 6,
    coverImage: "/article-media/crochet/pastel_blanket.png",
    checkoutEnv: "CHECKOUT_URL_RAINBOW_RIPPLE_BABY_BLANKET",
    checkoutUrl: "https://isafouat.gumroad.com/l/RainbowRippleBabyBlanket",
    leadMagnet: "/category/crafts/crochet/blankets",
    category: "crochet",
    ctaLabel: "Get the pattern ($5.99) →",
    includes: [
      "Digital PDF crochet pattern with row-by-row chevron instructions",
      "Written in standard US crochet terminology with clear stitch notes",
      "Full colorway sequencing and stripe transition guidance",
      "Yarn weight and hook recommendations for soft baby-safe drape",
      "Flat-laying border finishing and blocking tips",
    ],
    bestFor: [
      "Baby shower and newborn heirloom gifts",
      "Crocheters who love colorwork and rhythmic wave stitches",
      "Nursery, crib, and stroller blanket projects",
      "Confident beginners ready for chevron ripples",
    ],
    faqs: [
      { question: "What skill level is needed?", answer: "Confident beginner to intermediate. If you know chain and double crochet, the pattern walks you through peak increases and valley decreases step-by-step." },
      { question: "What size does the finished blanket measure?", answer: "Approximately 30 × 36 inches (76 × 91 cm) as written, with instructions on how to easily adjust the width by repeating the chevron multiple." },
      { question: "Is this a physical blanket or a digital download?", answer: "This is an instant digital download PDF pattern. You will receive immediate access upon purchase." },
    ],
  },
];

export function getShopProduct(slug: string) {
  return shopProducts.find((product) => product.slug === slug) ?? null;
}

export function productCheckoutUrl(product: ShopProduct) {
  return (process.env[product.checkoutEnv] || product.checkoutUrl || "").trim();
}
